### ISSUE TITLE
Divider Image on IE

### ISSUE THREAD

**Issue by wgranger** [zooniverse/liberating-the-liberator#119]
Very peculiar bug here. The divider.png isn't showing up on production with IE (it does show up on development and staging). However, all other static images (even pngs) appear fine. I'm using an IE11 - Win7 VM.

<img width="920" alt="screen shot 2017-10-25 at 10 53 12 am" src="https://user-images.githubusercontent.com/14099077/32008852-fb50d76c-b972-11e7-9e88-af7642cbee5c.png">

**Comment by shaunanoordin** [comment]
I don't see this issue occurring on either localhost or antislaverymanuscripts.org , using Win7+IE11 (VM) My only thought is to check if anybody else is seeing the problem - there doesn't seem to be any issue with the code, as far as I can tell.

**Comment by wgranger** [comment]
Ok. I'll close it for now. I was thinking it might be something particular with my local server or VM.
