### ISSUE TITLE
Add Linter to LtL

### ISSUE THREAD

**Issue by wgranger** [zooniverse/liberating-the-liberator#12]
Should we add a linter to this repo? The idea comes up when doing some PR reviews here. I personally like having a linter, but it's an open question. If we should decide to go that route, we'll also need to have a brief discussion about rules.

**Comment by shaunanoordin** [comment]
I usually feel pretty _meh_ about linters. I see the benefits of keeping the coding style consistent (especially with large-team projects like PFE) but anything other than the most basic settings (indent = 2  spaces, single quotes for strings, etc) tends to cause headaches. For example, working on a Windows machine sometimes gets me into trouble with some linter's CR/LF rules.

That said, don't we already have some some of linting function in LtL? I see there's `eslint` in our code, although I haven't checked if it's functioning as intended. I guess I'll try to code something using a double-quoted `"string"` and see if anything catches that faux pas.
