### ISSUE TITLE
Filmstrip Viewer Load Time

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/liberating-the-liberator#48]
## Fix Required
* This follows PR #45
* With the current implementation of the Filmstrip Viewer and multi-image Subjects, the Filmstrip viewer requests _all the images_ from the Subject _on load._
  * This means that as soon as you open the Classifier Page, you might be hit with, say, 10x requests for 1.2MB image - the page will load 10.2 freaking MB before you do anything.
  * This is bad for the users for a multitude of reasons, but the most pertinent to the project is that (if the initial Subject image isn't the first to be fully loaded) it could take users a whole minute before they can even start annotating.
* Fortunately, there is a solution on the horizon:
  * Use thumbnails for the Filmstrip Viewer instead of the full-res Subject images.

### Recommended Solution
* As Cam pointed out, the Zooniverse already has a thumbnail generatator-majig. (nginx?)
* For example,
  * If we want to convert the Subject image https://panoptes-uploads.zooniverse.org/staging/subject_location/87e48d7c-0a30-4ec7-9d31-47361a68db8f.png into a thumbnail,
  * we use this URL: https://thumbnails.zooniverse.org/250x250/panoptes-uploads.zooniverse.org/staging/subject_location/87e48d7c-0a30-4ec7-9d31-47361a68db8f.png
* This thumbnail URL would replace the full-size image URLs used in the Filmstrip Viewer component.

Further documentation, notably for setting the width/height/etc: http://nginx.org/en/docs/http/ngx_http_image_filter_module.html

### Further improvements 
* [minor] Currently the filmstrip viewer uses a hardcoded inline style to set the image to 40x60px (  `<img style="width: 40px; height: 60px">` )
  * This can be replaced with `width: 100%; height: auto;` to prevent any squishing/stretching of the preview image if that image doesn't match the 2:3 size ratio.

Tagging @wgranger ; while not a core/critical issue, addressing this will be a priority (categories: performance, usability) closer to launch or when the project has more testers/users on it.

**Comment by wgranger** [comment]
Nice. Also saw the convo in Slack. Thanks for the follow up with an issue. Should be a relatively quick add.
