### ISSUE TITLE
Discrepancies Between Production/Staging Webpack?

### ISSUE THREAD

**Issue by wgranger** [zooniverse/liberating-the-liberator#87]
There are a few issues with the production and staging versions of webpack. 

1) The favicon appears on staging, not on production
2) The AbeLincoln font is not imported correctly on production
3) Content/text is not pulled from the project resource on production

**Comment by shaunanoordin** [comment]
![screen shot 2017-10-13 at 19 01 28](https://user-images.githubusercontent.com/13952701/31559556-f40fde22-b048-11e7-867f-273343d8bd28.png)

Note the differences between localhost and production:
- Production's project description is blank. (Everything after "Welcome to Anti-Slavery Manuscripts")
- The font of the main h1 element is very, very different. Everything else seems OK, strangely.

**Comment by wgranger** [comment]
I noticed that if you compare the computed css between the two, the production environment is not receiving the AbrahamLincoln font, which makes me thing there is an issue with the import grabbing info from the fonts folder.

**Comment by shaunanoordin** [comment]
![screen shot 2017-10-13 at 19 15 01](https://user-images.githubusercontent.com/13952701/31560100-f42c0d0c-b04a-11e7-84d3-6793e5201648.png)

What is this. What is this madness.

Both localhost and production pull AbrahamLincoln.woff properly, but the file that production receives is the default FontAwesome web font. What.

**Comment by shaunanoordin** [comment]
OH SNAP

The server! Maybe the server doesn't serve `.woff` files? I know it serves `.ico` files, but perhaps there was some side effect of issue #76 's site config that doesn't identify `.woff` files as safe to serve, or something.

Compare these two files:
- https://www.antislaverymanuscripts.org/favicon.ico
- https://www.antislaverymanuscripts.org/AbrahamLincoln.woff

Perhaps this has to do with https://github.com/zooniverse/static/blob/master/sites/www.antislaverymanuscripts.org.conf#L12 ?
