### ISSUE TITLE
previousAnnotations data structure

### ISSUE THREAD

**Issue by wgranger** [zooniverse/liberating-the-liberator#97]
We need to give this a bit more thought. There is currently a bug on the frontend because `state.previousAnnotations.marks` is reset each time the frame changes, with `marks` corresponding to the **current** frame. Because of this, information such as `hasCollaborated` is lost each time the frame changes.

My initial thought was to make `state.previousAnnotations.marks` an object with keys such as `frame0`, `frame1`, etc. However, we would have to rethink this when a user visits his/her transcribing in a future session and `state.previousAnnotations.marks` is restructured. 

Perhaps there does need to be some sort of matching on the points of previous and user annotations? Thinking this through would solve some frontend issues.

**Comment by wgranger** [comment]
Also, as noted in #92, how can previousAnnotations point to current user annotations when deleting?

**Comment by shaunanoordin** [comment]
Temporary fix recommendation: make the Previous Annotations appear _before_ the user's Annotations. WARNING: This is super-cheating.

```
AnnotationsPane
      <g transform={imageOffset}>
        {this.renderPreviousAnnotations()}  //HELLO
        {this.renderAnnotationInProgress()}
        {this.renderUserAnnotations()}
      </g>
```

**Comment by shaunanoordin** [comment]
I'll take care of this quick fix by end of day.
